"""Score- and strength-adjusted team xG, built from the shot file.

The shipped xG team rating (the model's biggest feature, +0.00316 on TEST) is
updated on RAW xG margin. Raw xG is a biased measure of team strength for a
reason every public hockey model corrects for: a trailing team shoots much more
and a leading team sits back, so raw xG partly measures how the game went rather
than how good the team is.

This module reconstructs, from data/nhl_shots.csv alone, the running score and
the strength state at every shot, and emits per-game team xGF/xGA in four
flavours so phase0/nhl_xg_screen.py can screen them against each other:

  raw      every shot, unweighted (what ships today)
  adj      every shot, weighted by score state
  ev       even-strength (5v5) shots only
  adjev    5v5 only, weighted by score state

SCORE ADJUSTMENT. For score state s (the shooting team's lead, clamped to +/-3),
let F(s) be league-wide xG generated by teams sitting at s and A(s) be xG they
conceded. If score effects did not exist, F(s) would equal A(s) at every s. They
do not: trailing teams out-generate badly. The standard fix weights each shot so
that every state contributes a balanced share,

    w(s) = 2 * A(s) / (F(s) + A(s))

which is < 1 when teams at s out-generate (deflating the trailing team's
inflated volume) and > 1 when they are out-generated. w is 1.0 exactly when the
state is neutral, and the weights average to ~1 by construction, so adjusted xG
stays on the same scale as raw xG and the rating's tuned k does not have to move.

LEAK SAFETY. The weights are estimated on DEV seasons ONLY (2010-11..2017-18) and
then applied unchanged to every season including TEST. A weight table fitted on
all seasons would let TEST-era score effects define a TEST-era feature.

The score at a shot is the score BEFORE it: goals are applied only after the shot
that scored them is recorded, so a goal never adjusts its own weight.
"""
from __future__ import annotations

import csv
from collections import defaultdict

DEV_SEASON_MAX = 20172018        # weights come from DEV only; see module docstring
STATE_CAP = 3                    # +/-3 goals; beyond that the state is one bucket
FLAVOURS = ("raw", "adj", "ev", "adjev")

TEAM_FIX = {"PHX": "ARI", "ATL": "WPG", "L.A": "LAK", "N.J": "NJD",
            "S.J": "SJS", "T.B": "TBL"}


def _clamp(d: int) -> int:
    return max(-STATE_CAP, min(STATE_CAP, d))


def load_shots(path: str = "data/nhl_shots.csv"):
    """game_id -> shots in chronological order, each with score state and 5v5 flag.

    Yields per game so the 1.75M-row file is never fully materialised as dicts.
    """
    cur_id, cur = None, []
    for r in csv.DictReader(open(path, encoding="utf-8")):
        gid = int(r["nhl_game_id"])
        if gid != cur_id:
            if cur_id is not None:
                yield cur_id, _annotate(cur)
            cur_id, cur = gid, []
        try:
            hs, as_ = float(r["home_sk"] or 0), float(r["away_sk"] or 0)
        except ValueError:
            hs = as_ = 0.0
        cur.append({"per": int(r["period"]), "sec": int(r["per_sec"]),
                    "team": TEAM_FIX.get(r["shooter_team"], r["shooter_team"]),
                    "is_home": r["is_home"] == "1",
                    "xg": float(r["xg"] or 0.0), "goal": r["goal"] == "1",
                    "ev": hs == 5 and as_ == 5})
    if cur_id is not None:
        yield cur_id, _annotate(cur)


def _annotate(shots):
    """Stamp each shot with the shooting team's lead BEFORE the shot was taken."""
    shots.sort(key=lambda s: (s["per"], s["sec"]))
    h = a = 0
    for s in shots:
        # the shooter's own lead: home shooter sees h-a, away shooter sees a-h
        s["state"] = _clamp((h - a) if s["is_home"] else (a - h))
        if s["goal"]:
            if s["is_home"]:
                h += 1
            else:
                a += 1
    return shots


def fit_weights(seasons: dict[int, int]):
    """{('all'|'ev', state): weight} from DEV-season shots only.

    seasons maps game_id -> season int; games outside DEV are skipped entirely so
    no TEST-era score effect can reach the weight table.
    """
    gen = defaultdict(float)     # (scope, state) -> xG generated by teams at s
    con = defaultdict(float)     # (scope, state) -> xG conceded by teams at s
    for gid, shots in load_shots():
        if seasons.get(gid, 99999999) > DEV_SEASON_MAX:
            continue
        for s in shots:
            scopes = ("all", "ev") if s["ev"] else ("all",)
            for sc in scopes:
                gen[(sc, s["state"])] += s["xg"]
                # the same shot is xG conceded by the opponent, who sits at -state
                con[(sc, -s["state"])] += s["xg"]
    w = {}
    for key, g in gen.items():
        c = con.get(key, 0.0)
        w[key] = (2.0 * c / (g + c)) if (g + c) > 0 else 1.0
    return w


def build(games_csv: str = "data/nhl_games.csv",
          out_csv: str = "data/nhl_team_xg_adj.csv"):
    seasons, teams = {}, {}
    for r in csv.DictReader(open(games_csv, encoding="utf-8")):
        gid = int(r["game_id"])
        seasons[gid] = int(r["season"])
        teams[gid] = (TEAM_FIX.get(r["home"], r["home"]),
                      TEAM_FIX.get(r["away"], r["away"]))

    w = fit_weights(seasons)
    print(f"score-adjust weights from DEV (<= {DEV_SEASON_MAX}):")
    for sc in ("all", "ev"):
        row = "  ".join(f"{s:+d}:{w.get((sc, s), 1.0):.3f}"
                        for s in range(-STATE_CAP, STATE_CAP + 1))
        print(f"  {sc:<4} {row}")

    n = 0
    with open(out_csv, "w", newline="", encoding="utf-8") as fh:
        cols = ["nhl_game_id", "team"] + [f"{k}_{f}" for f in FLAVOURS for k in ("xgf", "xga")]
        wr = csv.writer(fh)
        wr.writerow(cols)
        for gid, shots in load_shots():
            tm = teams.get(gid)
            if not tm:
                continue
            home, away = tm
            acc = {t: {f"{k}_{f}": 0.0 for f in FLAVOURS for k in ("xgf", "xga")}
                   for t in (home, away)}
            for s in shots:
                shooter = home if s["is_home"] else away
                other = away if s["is_home"] else home
                if shooter not in acc or other not in acc:
                    continue                       # team-code drift; skip the shot
                wa = w.get(("all", s["state"]), 1.0)
                acc[shooter]["xgf_raw"] += s["xg"]
                acc[other]["xga_raw"] += s["xg"]
                acc[shooter]["xgf_adj"] += s["xg"] * wa
                acc[other]["xga_adj"] += s["xg"] * wa
                if s["ev"]:
                    we = w.get(("ev", s["state"]), 1.0)
                    acc[shooter]["xgf_ev"] += s["xg"]
                    acc[other]["xga_ev"] += s["xg"]
                    acc[shooter]["xgf_adjev"] += s["xg"] * we
                    acc[other]["xga_adjev"] += s["xg"] * we
            for t in (home, away):
                wr.writerow([gid, t] + [round(acc[t][c], 5) for c in cols[2:]])
            n += 1
    print(f"wrote {out_csv} ({n} games)")


if __name__ == "__main__":
    build()
